---
apiVersion: v1
data:
  config.yaml: |
    #Update With Valid Config file
kind: ConfigMap
metadata:
  name: matrix-bridge-whatsapp-config
  namespace: matrix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-bridge-whatsapp
  namespace: matrix
  labels:
    app: matrix-bridge-whatsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-bridge-whatsapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/dockerfile-default: "true"
        app: matrix-bridge-whatsapp
    spec:
      containers:
        - command:
            - sh
            - -c
            - cp -n -p /config/config.yaml /data/config.yaml && if [ -d /data/registration.yaml ] ; then chmod 0700 /data/registration.yaml ; fi && ./docker-run.sh
          image: dock.mau.dev/mautrix/whatsapp:v0.8.2
          name: matrix-bridge-whatsapp
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: matrix-bridges-data
              subPath: "whatsapp"
            - mountPath: /config/config.yaml
              name: matrix-bridge-whatsapp-config
              subPath: config.yaml
      restartPolicy: Always
      volumes:
        - name: matrix-bridges-data
          persistentVolumeClaim:
            claimName: matrix-bridges-data
        - name: matrix-bridge-whatsapp-config
          configMap:
            name: matrix-bridge-whatsapp-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-bridge-whatsapp
  namespace: matrix
  annotations: 
    dns.alpha.kubernetes.io/external: "mautrix-bridge-whatsapp.matrix.svc.cluster.local"
spec:
  selector:
    app: mautrix-bridge-whatsapp
  ports:
  - name: http
    targetPort: 29318
    port: 29318
